### PR TITLE
Engine to provide user hardcoded functions

### PR DESCRIPTION
**Pull request by judovana**
Hello! This PR is enhancing ParserNG for user hardcoded functions. To make it possible, I had to make small refactroing. The [Removed duplicated declarations of stats methods](https://github.com/judovana/ParserNG/commit/4b3bfc5b1f7284c0c82a50d2af411055b36505c5) is moreover a must.  The [Moved declarations of methods to separate class](https://github.com/judovana/ParserNG/commit/5253b9b1b4b22f98556b3ef3e62d97853de4c50b) is a bit disputable, but I think it is benefit,e specially with [Added prototype to register custom hardcoded basic numerical methods](https://github.com/judovana/ParserNG/commit/835a2aff4cd201fbb4520fb08c57075a842f152f) in mind. The [Added initial help for embedded functions](https://github.com/judovana/ParserNG/commit/c7cbf1ed730605384b1d219e57556d057e86667e) is just useful.

The [Added prototype to register custom hardcoded basic numerical methods](https://github.com/judovana/ParserNG/commit/835a2aff4cd201fbb4520fb08c57075a842f152f) is making the static array of functions dynamic, wich may have very slight performance impact. But afaik, where the performance remains very good super high performance is not exactly main goal of this library.
It is disputable whether to add new functions ass class definitions, and instantiate on every new usage by reflection, or by instance, and to reuse it I had chosen instance, as it seems to me more usable, and more nice. However if the functions will start to be statefull, the class declaration will need to surpase the  instance.

I do not have any hard feelings if you reject it all. On short run, my intention was to add avgN and geomN functions,  which would do average, but on sorted list, and with cut of N - possibly extreme - values on both ends cut off. I had, yet again, fiaeld to implement them as pure String,  and when time come to hardcode them, I thought I would make it more proeprly.

In next commit(s), I will replace WeirdFunction class by the geomN and avgN. Maybe together with extracting sort, geom and avg, simply just for easy reuse.

### CODE REVIEW

**Comment by judovana** [comment]
Hello!

I will soon forget what I have done!-)

**Comment by gbenroscience** [comment]
Oops, just give me a little time. Will reach out to you

**Comment by judovana** [comment]
Sure:)

**Comment by judovana** [comment]
ayay.. Am already forgetting!

**Comment by gbenroscience** [comment]
> ayay.. Am already forgetting!

Lol, will be with you soon

**Comment by gbenroscience** [comment]
> Hello! This PR is enhancing ParserNG for user hardcoded functions. To make it possible, I had to make small refactroing. The [Removed duplicated declarations of stats methods](https://github.com/judovana/ParserNG/commit/4b3bfc5b1f7284c0c82a50d2af411055b36505c5) is moreover a must. The [Moved declarations of methods to separate class](https://github.com/judovana/ParserNG/commit/5253b9b1b4b22f98556b3ef3e62d97853de4c50b) is a bit disputable, but I think it is benefit,e specially with [Added prototype to register custom hardcoded basic numerical methods](https://github.com/judovana/ParserNG/commit/835a2aff4cd201fbb4520fb08c57075a842f152f) in mind. The [Added initial help for embedded functions](https://github.com/judovana/ParserNG/commit/c7cbf1ed730605384b1d219e57556d057e86667e) is just useful.
> 
> The [Added prototype to register custom hardcoded basic numerical methods](https://github.com/judovana/ParserNG/commit/835a2aff4cd201fbb4520fb08c57075a842f152f) is making the static array of functions dynamic, wich may have very slight performance impact. But afaik, where the performance remains very good super high performance is not exactly main goal of this library. It is disputable whether to add new functions ass class definitions, and instantiate on every new usage by reflection, or by instance, and to reuse it I had chosen instance, as it seems to me more usable, and more nice. However if the functions will start to be statefull, the class declaration will need to surpase the instance.
> 
> I do not have any hard feelings if you reject it all. On short run, my intention was to add avgN and geomN functions, which would do average, but on sorted list, and with cut of N - possibly extreme - values on both ends cut off. I had, yet again, fiaeld to implement them as pure String, and when time come to hardcode them, I thought I would make it more proeprly.
> 
> In next commit(s), I will replace WeirdFunction class by the geomN and avgN. Maybe together with extracting sort, geom and avg, simply just for easy reuse.

Thanks for the effort.
A major future goal of this library, even though not obviously stated is performance, and it would be really helpful to keep that in mind, as we build along. 
(I know some of the things that make the library take a performance hit anyway and will work on them in the future, if God permits.)



> It is disputable whether to add new functions ass class definitions, and instantiate on every new usage by reflection, or by instance, and to reuse it I had chosen instance, as it seems to me more usable, and more nice. However if the functions will start to be statefull, the class declaration will need to surpase the instance.

It would be undesirable to introduce reflection in any way into the picture, precisely for this reason, as it would constitute a major speed bottleneck. You dont want a laggy operation to kick in while plotting a graph, or performing a long calculation and all that.

The registering of user hard coded functions is a cool feature though, if we can get it right. I noticed that you are using some syntax from more recent versions of Java, though. We wont be able to fly with it in the current state due to backwards compatibility issues on Android and other platforms. But I am willing to reconsider if you can get it right.

Thanks again for  your hard work. And apologies for the delay

**Comment by judovana** [comment]
Ok. Understood. In that case I'm happy I had  not introduced the reflection, and will not during this PR, nor i the custom function.
Will remove the jdk 7 features now. TY!

**Comment by judovana** [comment]
hmhm. I had looked into the parts where I used the streams - are you sure you wish to stay on jdk7 language? It is jdk17 which is now new, not 8.  Also all live androids seems to be on newer JDK then 7... But yah.. nvm :)

**Comment by judovana** [comment]
Hello adapted as requested. Any more hints sir?

**Comment by judovana** [comment]
ping please?

**Comment by judovana** [comment]
== can we merge pls?

**Comment by judovana** [comment]
Please?

**Comment by gbenroscience** [comment]
Apologies for being away for so long.
The only blocker I have at this point with this merge, will be the fact that your PR does not support multiple brackets.
Will you be able to fix this in the nearest possible future?

**Comment by judovana** [comment]
Sure. I agree it is blocker. Still thee PR should not remove multiple brackets support. Do you have example?
In meantime I will elaborate and add test for them.

**Comment by judovana** [comment]
Test added. Seems to be ok?

**Comment by gbenroscience** [comment]
> 

I will check what you have and get back to you.

**Comment by judovana** [comment]
Just for record, please do not squash/squeeze  commits in case it crossyour mind. They are necessary to land as they are.

**Comment by gbenroscience** [comment]
> encessarty

I do not understand, the last comment

**Comment by judovana** [comment]
Fixed, sorry for double typo.

Thank you for merging.  I have few more PRs to do after the vacation period ends around. Hopefully they will be smaller and more easy to review. TYVM for awesome library.

**Pull request merged**
