### PR TITLE
Degrees/Radians/Grads can now be set globaly by property/variable

### PR DESCRIPTION
**Pull request by judovana**
setDRG function in i api remains

sh-5.2$ RADDEGDRAD_PNG=DEG java -jar  target/parser-ng-0.1.8.jar  "sin(90)" 1.0
sh-5.2$ RADDEGDRAD_PNG=RAD java -jar  target/parser-ng-0.1.8.jar  "sin(90)" 0.8939966636005579
sh-5.2$  java -jar  target/parser-ng-0.1.8.jar  "sin(90)" 0.8939966636005579
sh-5.2$ RADDEGDRAD_PNG=DEG java -jar  target/parser-ng-0.1.8.jar  "asin(1)" 90.0
sh-5.2$ RADDEGDRAD_PNG=RAD java -jar  target/parser-ng-0.1.8.jar  "asin(1)" 1.5707963267948966
sh-5.2$ RADDEGDRAD_PNG=RAD java -jar  target/parser-ng-0.1.8.jar  "asin(0.8939966636005579)" 1.106186954104004
sh-5.2$

### CODE REVIEW

**Comment by gbenroscience** [comment]
Can you check the conflicts or discard this PR?

Also, what is the justification for this PR?
Thanks

**Comment by judovana** [comment]
Hello! Will fix the conflict once am at pc. Justification? Was there some way how to control whether the library works in rad/deg/grad? If so, i have not found it and am sorry for overlook.  I saw only harcoded rads.  As i had not found it, i creaTed this pr. Now you can set it for each MathExpression, and set default rad/grad/deg on startup as read only, or via property,  so adjustable durin runtime(see the test in commit). Looking forward for feedback!

**Comment by judovana** [comment]
Btw, nearly all the logic was already  there, was just not used. Needed just a bit of poking

**Comment by judovana** [comment]
rebased

**Comment by gbenroscience** [comment]
Lol! of course you can set it per MathExpression from the very first push of ParserNG.
Offhand, it should be expr.setDRG(val) or something similar.

I will take a look at your approach which seems to be more elaborate though, and see its merits.

**Comment by judovana** [comment]
The usage of setter was weird. And there was no global setup either.  But as I was saying, the logic was moreover here, and just needed a bit of poking. Thanx!

**Pull request merged**
