### PR TITLE
now really adding avgN via forgotten AvgN.java

### PR DESCRIPTION
**Pull request by judovana**
In previous commit, an git add above newly added files was forgotten,
so ParserNG had not even build.
This is adding missing files.

### CODE REVIEW

**Comment by judovana** [comment]
My apologies for this. I will add github integration to catch those.

**Comment by gbenroscience** [comment]
There are errors in your build. Please fix

**Comment by judovana** [comment]
I had just double check (after seeing your comment). Fresh clone of master  builds without test failure and some manual testing do not relieve anything more.
Can you please share details?

**Comment by judovana** [comment]
The only issues I see are int he new AvgN function, where the trimming of  tokens list have not covered corner cases.Am on them right now. But may not finish today

**Comment by judovana** [comment]
Oh you mean the failed CLI on windows? Hmm. I have not seen windows fot two decades. You have clues?
```
mvn --batch-mode --update-snapshots clean install -Dgpg.skip
...
[ERROR] Unknown lifecycle phase ".skip".
```
Thoughts?

**Comment by gbenroscience** [comment]
Not sure...,  try:
`mvn --batch-mode --update-snapshots clean install -"Dgpg.skip"`

instead of

`mvn --batch-mode --update-snapshots clean install -Dgpg.skip`

**Comment by gbenroscience** [comment]
If that doesn't work, try:

`mvn --% --batch-mode --update-snapshots clean install -Dgpg.skip`

Also, [check this material](https://github.com/Azure/azure-sdk-for-java/wiki/Building) for more information.

**Comment by judovana** [comment]
Oh yah. Power shell.  never heard of that :) Thanx for link!  Had submitted PR with fix.

**Pull request merged**
