### PR TITLE
Proper main

### PR DESCRIPTION
**Pull request by judovana**
This PR is adding proper main method to library, so it can be properly used from commandline both via arguments and via stdin/pipes.
MathExpression main works as expected, and ParserCmd logic remained unchanged

Junk from original main in MathExpression changed to test, including the "benchmarks"
Readme updated, section for command line will be in the next commit

### CODE REVIEW

**Comment by judovana** [comment]
The fail in jdk8 is veeery interesting!

**Comment by judovana** [comment]
btw, 1.7 is still not out :(( I really need to use it (https://mvnrepository.com/artifact/com.github.gbenroscience/parser-ng)

**Comment by judovana** [comment]
Hello! You there?

**Comment by judovana** [comment]
Tyvm!

**Comment by gbenroscience** [comment]
> Tyvm!

Forgive me, brother

**Comment by gbenroscience** [comment]
I just pushed to maven, its coming out under 0.1.8, due to some errors in publishing. Its not showing yet on search.maven though.

**Comment by judovana** [comment]
Awesome! Ty Sir!

**Comment by gbenroscience** [comment]
The update is finally live on [maven](https://search.maven.org/artifact/com.github.gbenroscience/parser-ng/0.1.8/jar)

**Comment by judovana** [comment]
FYI, parseng is now being packed for fedora: https://bugzilla.redhat.com/show_bug.cgi?id=2141688

**Comment by gbenroscience** [comment]
Wow,cool! 😎

**Comment by judovana** [comment]
https://koji.fedoraproject.org/koji/packageinfo?packageID=36386

Here we are!

**Comment by gbenroscience** [comment]
Wow! Good work! Thanks for all you do for ParserNG!

**Pull request merged**
