### PR TITLE
Added round, roundN and abs functions

### PR DESCRIPTION
**Pull request by judovana**
There is already ceil and floor, but natural is  missing. Added. Added also with N version, which allows to set number of *fractional* points we are interested in.

### CODE REVIEW

**Comment by judovana** [comment]
Current  main functions added:
```
round(121.5) ->  122
```
```
roundN(3,121.5) ->  121.5
roundN(2,121.5) ->  121.5
roundN(1,121.5) ->  121.5
roundN(0,121.5) ->  122
```
```
roundDigitsN(4,121.5) ->  122.5
roundDigitsN(3,121.5) ->  122
roundDigitsN(2,121.5) ->  120
roundDigitsN(1,121.5) ->  100
roundDigitsN(0,121.5) ->  121.5 //as default in java implementation
```

I'm using rounding 5 up. Do you wish also rounding of 5 down?

**Comment by judovana** [comment]
hmm. That may actually lead to need t roundUp and round down as 5 is ususally roundable by both dirrection, depends on usecase and locale. Its probably on yours preference.

**Comment by judovana** [comment]
hmm. It behaves somehow weird around the zero. I think I may be failing primary school maths...

**Comment by judovana** [comment]
ok, fixed. Btw - how many valid digits have 0? I expect none. right?

**Comment by judovana** [comment]
Hello!

I had noted, that expressions for new functions do nto behave as expected:
```
        me = new MathExpression("round(sin(5))");
        Assertions.assertEquals("-1", me.solve());
        me = new MathExpression("round(abs(-1.5))");
        Assertions.assertEquals("2", me.solve());
```
is ok
however
```
        me = new MathExpression("round(3/2)");
        Assertions.assertEquals("2", me.solve());
```
Is not, as 3,/,2 is send into round function.

In addition
```
        MathExpression me = new MathExpression("avgN(0,4+0,2+0)");
        Assertions.assertEquals("3.0", me.solve());
```
is ok
and even 
```
        me = new MathExpression("avgN(0,round(0.5),round(0.5))");
        Assertions.assertEquals("1", me.solve());
```
But 
```
        me = new MathExpression("round(avg(0,3/2,2/3)");
        Assertions.assertEquals("0.7", me.solve());
```

Is not.


PLEASE, do you have any clues why?

**Comment by judovana** [comment]
The new tests on this behaviour are causng hte check failures.

**Comment by judovana** [comment]
I'm pretty sure I was testing 
```
 me = new MathExpression("round(3/2)");
        Assertions.assertEquals("2", me.solve());
```
since origin... what changed where...

**Comment by judovana** [comment]
digging digging:
```
roundN(2,2/3)
0.67
```
 works correct
```
roundN(0,2/3)
1
```
also. So the presence of "," sounds as trouble.
However:
```
avg(5)
5
```

rounds  also correct. But avg is still embeddedm and all recently added  geomN and avgN takes more then one argument.

**Comment by judovana** [comment]
hmm. Looks like this issue is here since ever:
```
sum(3/2)
SYNTAX ERROR
```

**Comment by judovana** [comment]
So it seems that parserNG is buggy in this, and Statistic functions can not take only one parameter. Will you be able to fix it?

I built the BAsicNumericFunction on assumtion (damn me!) that statistic functions can take one parameter.

**Comment by judovana** [comment]
Had jsut checked an older version:
```
 java -cp  /home/jvanek/.m2/repository/com/github/gbenroscience/parser-ng/0.1.5/parser-ng-0.1.5.jar   parser.cmd.ParserCmd
Welcome To ParserNG Command Line

Question 1:
______________________________________________________
sum(3+2)
Answer
______________________________________________________
SYNTAX ERROR

Question 2:
______________________________________________________
sum(3+2,1+1)
Answer
______________________________________________________
7.0

```

damn :(

**Comment by judovana** [comment]
oh this is funny:
```
Question 3:
______________________________________________________
sin(1+1,2+2)
Answer
______________________________________________________
0.9893582466233818

Question 4:
______________________________________________________
sin(1+1)
Answer
______________________________________________________
0.9092974268256817

Question 5:
______________________________________________________
sin(2+2)
Answer
______________________________________________________
-0.7568024953079282

```

What is the `sin(1+1,2+2)`  doing?

**Comment by judovana** [comment]
Generally, waht was the reason to treat stat functions and other differently?

**Comment by judovana** [comment]
Ok. I have debugged it pretty deep
```
        //ParserNG iincorrectly solve sin(1+1,2+2) as  sin(2 4)  which is sin(2*4)
       MathExpression("sin(1+1,2+2)").solve() ==  MathExpression("sin(8)").solve()
```

But I do not see any easy way to fix it.

I can  **workaround** it in  _ext_  functins, that fucntions taking one argument like abs or round (but not functions taking more like roundX or geomN )  will call new MathExpression(tokens.join(" ").solve() upon its arguments before it actually proceed into itself.

I can fix current buggy sum/prod.. and other fucntions by convert them to ext function and  and do a similar trick when only one argument is present.

I can fix current buggy sin/cos... and other fucntions by converting them to ext function.

As a result, the divergence between stats and purely numeric functions will disapear where possible.

I can not proceed, until you provide an expalnations which may lead me to correct track  or out of dead end.

**Comment by judovana** [comment]
Somewhere around, some `comma` does seomthig really bad.. Looking forward for your comment ;)

**Comment by judovana** [comment]
Issu shown at https://github.com/gbenroscience/ParserNG/pull/23
Fix shown at https://github.com/gbenroscience/ParserNG/pull/24

**Comment by gbenroscience** [comment]
So sorry  @judovana.
Your issues are coming from some place pretty deep within the scanner. I will fix as soon as I can.

**Comment by judovana** [comment]
I know. Thats why I created PR#26 which you just closed. To be able to workaround it before - if ever - fix is found. Please reopen PR#26, review and merge if possible! Wihtotu it I can not contiue in downstream projects.

**Comment by judovana** [comment]
Once this is rebased to soem final version of #26 it will be ok. At leaste untill it si properly fixed - if ever.

**Comment by judovana** [comment]
> So sorry @judovana. Your issues are coming from some place pretty deep within the scanner. I will fix as soon as I can.

It is caused by issue https://github.com/gbenroscience/ParserNG/issues/25

please reconcile #26 !

**Comment by gbenroscience** [comment]
> So it seems that parserNG is buggy in this, and Statistic functions can not take only one parameter. Will you be able to fix it?
> 
> I built the BAsicNumericFunction on assumtion (damn me!) that statistic functions can take one parameter.

I just fixed it, lol

**Comment by gbenroscience** [comment]
Can I merge this now?

**Comment by judovana** [comment]
TYVM!  I had rebased (and fixed as needed) also remaining three PRs.  Looking forward for merge/review.

**Pull request merged**
