### PR TITLE
Added geom, gsum and count functions

### PR DESCRIPTION
**Pull request by judovana**
Hello!

I was originally going to implement the geometrical average in your calculus, but found the crucial count function missing (as I have data for your calculus generated), so i dared to implement the geometrical average in the project itself.

When in it,  I had enabled tests, added tests to new methods, and added minimal gitignore

The tests are however not passing. Count is ok, but for some reason geom and fcount fails similarly:
```
DETECTED ERROR! IN [(, g, *, e, *, om, *, (, 2, 8, 4, ), )]
```

I guess I had forget to declare somewhere  that thye are functions... Any clue?

### CODE REVIEW

**Comment by gbenroscience** [comment]
Hi @judovana. Thanks for your interest in ParserNG, and for your boldness to look into the codebase.
First what do you mean by **crucila**.
Also, I do not understand what you mean by **_(as I have date for your calculus generated)_**

Please shed more light on these, so I can know what you are trying to do and how to help.
Thanks again

**Comment by gbenroscience** [comment]
Please add the function signatures for the newly implemented `geom`, `fcount` and `count` also

**Comment by judovana** [comment]
Hello! Thanx!. Both typos fixed (crucial and data generated)
Ah..signatures! Sure. Will add them! TY!

**Comment by judovana** [comment]
hmm.. Searching searching - where/what are the signatures?

**Comment by judovana** [comment]
I tried to change the return from BigDecimal to double  as `count` works fine. But did not helped. I had also tried to rename them to csum and ceom.(to be more close to working count).  Just for record, had not helped. Turning  on debugger now.

**Comment by gbenroscience** [comment]
@judovana , did you add your new functions to the `inbuiltMethods` array?
The function signature is simply the expression of how the function is used...e.g. for `sin`, it is something like `sin(number) `.

**Comment by gbenroscience** [comment]
> hmm.. Searching searching - where/what are the signatures?

I mean, type out the function signatures here, so I can see what they look like

**Comment by judovana** [comment]
Yah, I added. When I rename functions to `blah` and  `blob` it will start to work.
The issue is, that `sum` is known function, so `gsum` is interpreted as `g*sum` before anything else. the i the geom, I'm less sure, as it gets interpreted as `g*e*om*

I think I added them everywhere correctly (especially if they works fine after rename)

**Comment by gbenroscience** [comment]
I checked your commit. You have not added your functions to the `inbuiltMethods` array.

**Comment by gbenroscience** [comment]
Also, the parser knows how to deal with function names like sum and gsum... that is why it can handle: `sin` and `sinh`, `cos` and `cosh`, `tan` and `tanh`

**Comment by gbenroscience** [comment]
Check line 147 of this file: [Method.java](https://github.com/judovana/ParserNG/blob/geomGsumCountTests/src/main/java/parser/methods/Method.java).
You will see the `inbuiltMethods` array there.
Add the function names to it.

**Comment by judovana** [comment]
Shame on me. How could I overlook it... and the accidentally working "count" mislead me.
Commit ammended. TY!

Will you be so kind and do a maven release once the commit is to your liking?

**Comment by gbenroscience** [comment]
Good work. I will review the commit as soon as I can. But I have to inform you that I am a bit preoccupied at the moment. Still, I will try my best.

**Review by gbenroscience — CHANGES_REQUESTED** [review]
There are lots of typos in your commit descriptions:
enabeld should be enabled for instance, impelmented should be implemented.
Also, the use of the word calculus is a bit too liberal here, since the domain is mathematics, and one might easily misconstrue your usage of calculus for differential calculus(differentiation) and integral calculus (integration)

**ACTION**
Please rename the BigDecimalRootCalculus to reflect this

**Comment by judovana** [comment]
Hello!

Thanx a lot for review.  All issues should be addressed. Sorry for typos (fixed), it is my nightmare:(
With the release, do not feel any press.  I will release my (depnding) pacakage once you release  this one. As I need geometrical average.

**Comment by judovana** [comment]
TY!

**Comment by gbenroscience** [comment]
Lol! You are welcome. I have pushed to maven central, so you can keep checking once it is live.
It is already showing [here](https://repo1.maven.org/maven2/com/github/gbenroscience/parser-ng/0.1.6/) , but it doesn't show [here](https://search.maven.org/artifact/com.github.gbenroscience/parser-ng) yet.

Could you give me a heads up when it goes live?
Thanks!

**Comment by judovana** [comment]
Hello!
If you pushed to maven central, and commit with new version (0.1.5.1 or 0.1.6) should follow. otherwise you could have pushed as 0.1.5 which is probably not what you want, and IDK how it can behave.

**Comment by gbenroscience** [comment]
No, it was pushed as 0.1.6.
I think it takes a while to reflect on maven central... like I said, it already shows 
[here](https://search.maven.org/artifact/com.github.gbenroscience/parser-ng)

**Comment by judovana** [comment]
Yah. But the commited pom.xml still shows 0.1.5  - https://github.com/gbenroscience/ParserNG/blob/master/pom.xml#L6 (and so does readme.md ). Sorry for nitting.

**Comment by judovana** [comment]
Just for record: https://github.com/gbenroscience/ParserNG/pull/11

**Pull request merged**
