### PR TITLE
Added workaround to issue 25 for statistic function

### PR DESCRIPTION
**Pull request by judovana**

### CODE REVIEW

**Comment by judovana** [comment]
the CI failure was download timeout.

**Comment by gbenroscience** [comment]
Must remove this once issue isbfixed in core parser

**Comment by judovana** [comment]
Wait. You ahve it already fixed? If so, then it is ok to close. Otherwise it shoudl be merged.
In addition, the  extracted fucntions are jsut good. so they can be merged too.

Long story short, this should go in, and the workarounding function shoudl be removed/adapted once parser does what it should.
Can you please reopen, until the issue is resolved?

**Comment by judovana** [comment]
This is NEW pr. I already closed that one, which was not agree on and was just pinpointing issue, and proposeing hot fix.

**Comment by judovana** [comment]
One more note - you closed. not merged. Not sure if it was intentional. If it was intentional, please, reconcile.

**Comment by judovana** [comment]
Please, reopen and reconsider this PR - unless the https://github.com/gbenroscience/ParserNG/commit/7d39d70eed4334a516c114d838a787a9a2d8a069#diff-7592ec3fb1f62c29d86d7c8c826fc5a684c85caee27fc35b7b6c3c5628bc47e1R96 is completely wrong by you. If so, please provide other workaround or guidance.  The workarounding method is easily removable once the issue is fixed. 
parserNG should provide a unified method how to workaround the issue in itself, otherwise any depending project will implement theirs own workaround. Similarly,the most fundamental statistic methods should work out of the box.

If you really so heavily disagree with https://github.com/gbenroscience/ParserNG/commit/7d39d70eed4334a516c114d838a787a9a2d8a069#diff-7592ec3fb1f62c29d86d7c8c826fc5a684c85caee27fc35b7b6c3c5628bc47e1R96 and with this PR, I need to know what you consider as good, as issue#25 ,  as known bug, is  blocker to any release of depending projects.

**Pull request merged**
